//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList_Hassan_El_Bardan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class main
    {
        public int Id { get; set; }
        public string Titel { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> Kategorie_Id { get; set; }
        public System.DateTime Anlegedatum { get; set; }
        public System.DateTime Änderungsdatum { get; set; }
        public string Verantwortlicher { get; set; }
        public bool isDone { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
    }
}
